---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-rbac
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/cluster0/rbac
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-cluster0
