apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: home-assistant-db-backup-v18
  namespace: databases
spec:
  schedule: "0 0 0 * * *"  # At midnight every day
  backupOwnerReference: self
  immediate: true
  cluster:
    name: home-assistant-postgres-v18
