apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:QZfOOtgZ5i9QJXvfJ4olLw==,iv:PYJCzT5R/5K7wyFJKlqKgMa6z9KP7vZ7weY8UoA1X8Y=,tag:8fKWAdoycAj7ONLIWuW8yg==,type:str]
    SECRET_PUBLIC_IP: ENC[AES256_GCM,data:D5yB6tC3wsyb2QKy,iv:YFyILJKjxDQjltWumRcOlneP/9uXA8wSZaaOb129Nz4=,tag:Bt1AqECx0Yzxqr64oJB/BA==,type:str]
    SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:iqidOQWRvNM7UCuhPMfr4t+a1Co=,iv:JJZtZs2dnN4oW9CrwSrbPLvgIh/r6Waqo3y3cp8QEco=,tag:QJACNJ6+PywKJC6CFq3KMQ==,type:str]
    SECRET_NOTIFICATION_EMAIL: ENC[AES256_GCM,data:wefy7vCTKAyfGe7Ug8gBAfus755Jof5EOYUBEOuB,iv:IojvzdbiN/NQpbEzMRWASR/gP1ty0jepI21oWXvadk4=,tag:HfExf4SzR1JO9IqR7a129g==,type:str]
    SECRET_TEST_EMAIL: ENC[AES256_GCM,data:mPOGVI6sJLYwK1DxM/+6xl7evnL/,iv:lbNuA2Vxu+XlCDfu/WCS53TlwM4Zqt5XaDOyU7Ci7Sg=,tag:TQjODcwxrP9UAL5ewmS14w==,type:str]
    SECRET_PARTNER_EMAIL: ENC[AES256_GCM,data:XBDTC6hnlzU1PN6bSaC31gmAsgOx,iv:ekv/XJK+3nxvwUL0FBAlyDFjLVvALFEKHQSaUBiq/pY=,tag:fVuF8K7krmvtAIXrJjX/Ag==,type:str]
    SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:z/EkPHno1w/vn0A+Fv8LRx45nnEjeg==,iv:6knudrrgoc1oiB7GKbOTG/7IjfOs6ORS1eo6yWq6AqI=,tag:yfyHLxu9IEDCHaoXXGJqFw==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:e137FunLFp/zgZTejltp5px7Mzg=,iv:ZllaT9U0BkH/J0Lg80tqzQnGIhiAlwLST/FpUqAx6nk=,tag:8zwlmWSuCqAfIlooZ8S47g==,type:str]
    BLOCKY_VALKEY_PASSWORD: ENC[AES256_GCM,data:Y78mT97NoNHyoySgyfkJpyp+2KbUMD7nRtM/ovyCc4UkB3rYNdvjoJM5jvb2xwhStI1f8U1QeMbCU7ZC1MvVbpaShqucviGkl0nUUvZE9k4cn8qLa/R+44xp61Kb2tHG9c9f8w==,iv:GHaVu/sM+gE4dAJBrlHQ0FGZh6vAoyeq1WEu54UVfv0=,tag:cf+/C8NvAG1j21jES5STGw==,type:str]
    SECRET_CNPG_SUPER_USER: ENC[AES256_GCM,data:X1QHxSsITxc=,iv:hyan3AyaTyJQlOBcM1KApdfhf77a5V0axfopdWY80i0=,tag:le4MW4x3SqBjZpZaDlcQcA==,type:str]
    SECRET_CNPG_SUPER_PASS: ENC[AES256_GCM,data:bSI/IzYIr+QmBX3TGcHPS7iRji07GRV/qLYM6OzAvRjjfuR/Lcq/k03U2v2MrBABJhhyPfKywvKjpKUoXmbH2xq0W7AXcDkJcsLW5PV8vB4q51TzsllOLyw5ZstdDkUtxRCqvpzq9UA4xdpz/O1GxqprfwFsg4roBDUyowFAS5g=,iv:FLldE6tbShO84ctij1tRpXCn3zXMfQsKVTsQEJzRRpc=,tag:XXCJRKCrkhzsO+NzljvjjQ==,type:str]
    SECRET_CNPG_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:pKnojA==,iv:Pi9l8J4c9UiCQL/pjD/cqJPj2yZ6p2HTbvHkbbJDD2c=,tag:XQ/hu3piiY6r0WxfXkidQQ==,type:str]
    SECRET_CNPG_MINIO_SECRET_KEY: ENC[AES256_GCM,data:iUuGuv4o0MSd2fvxEt+FWmXPk9WO3/S5yoW0HvV9kPVZogSiGUuGww==,iv:kkjPZB/w1BBO9Y56w6DznuLePc+Bm0ZffTiTu2QXG8I=,tag:ZzZK4zWAgJjNNV+n5GCJOg==,type:str]
sops:
    age:
        - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MTBCZVdoWmxxNVR1QVlz
            d3VNMlFuQkZUVjBjUHB3eHEzSUJlYnRJQkY4CkFnRTd2Sjc0M2JjMFYzUmdKSWg1
            M1kxb2pHQy9PaXBnQlhNdjJwNXF0ZHcKLS0tIG85b2NXeGpadkh2UCtGcHlWa2wv
            QmJsTmNKYWhnZk1kZVordXJMWU05Q0UKT3thBBU1GZ6IvJwwNimN5vuzLbIisYTH
            cXmung5xtnlpOaQUKhCvu0TIFS/qNCReLjP89/t2s38G3qKo0IY5Wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBER2dmeFFFbnBiRlVyRnlq
            NmdyTW52VVZEaDVFUTRTSzk4bEJ4TDBSUmx3CnYxMG5pc3U4eWZDMmF5VnBiUXJS
            MzByMm9YcEJXS1o1VXFscFN2dWU5Z3MKLS0tIGlXOFBYYzlubHNPNFlUVFdCd0JB
            ZGE3a3NybXlpOTVacWpkelI3aE1xcW8KHc0pa4IPNc2V/1t6t5yTghdRlUio7Op/
            FCLLJSgbKFW5UXXBjtuDpkAtp6Pj5jZtrBJN45zATUUz1PnSvUfRxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T03:18:35Z"
    mac: ENC[AES256_GCM,data:mi30A45M5ENqUy/9kMJ5PkgVo0wa0lum0A3AkBlstxDhBaLhDQKaPGAr8KcGRVWBSDFbHD4AhF2GHC99ShsY1FYYRmEQk+Mv3mDzACIpT5odA1u8qX3bWPVzL7rd2kz54vdkQL5O9ZWW313sjBLhGDKoo4dIValtR7fwV5Z/VY8=,iv:5Z5yMidozmLrBzPvJ6PXHQ3gQIWmkT9eCqmGqIDYdyc=,tag:oibhBGnlPfp+U61gCjYxhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
