---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_NAME: "home-ops-cluster0"
  TIMEZONE: "Pacific/Auckland"
  CONTROLPLANE_IP: "10.87.42.0"
  LOADBALANCER_IP_POOL: "10.87.42.10/27"
  TRAEFIK_IP: "10.87.42.10"
  PRIMARY_DNS_IP: "10.87.42.11"
  SECONDARY_DNS_IP: "10.87.42.15"
  PLEX_IP: "10.87.42.12"
  MOSQUITTO_IP: "10.87.42.13"
  SYNC_ENDPOINT: "10.87.42.14"
  # external service IPs
  NAS0_IP: "10.87.1.200"
  UNIFI_IP: "10.93.0.1"
  OCTOPRINT_IP: "10.93.149.56"
