apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:KxdBQBt/9F5C+QdW1+tbNw==,iv:ypK9hTl9cpL3Zrwj5+cAPQvorfPWM3+z/XYUSjVwYkg=,tag:M9wT+m8NBYdGe+sZ8GuE+A==,type:str]
    SECRET_PUBLIC_IP: ENC[AES256_GCM,data:79YMQWhgtVsNsHqf,iv:j0J88OE9DMKoU9Tr7ENf9S30pdmhNI7tUri2PW7SNd8=,tag:xaLt+azhxGuIvcY7gaDeKg==,type:str]
    SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:Wi0pL2UWtXZXChWp9s7IKi9T+eU=,iv:xoF1cZxT35t7FAsjFoDVTQ/hnO7dMvA6R+kgPasVU/E=,tag:lmXkMlvOBLHn7CHrfOJ7Ew==,type:str]
    SECRET_NOTIFICATION_EMAIL: ENC[AES256_GCM,data:zea3N3bl2fNznbX7rja8Sd5A1Ngovk0t4TNx1pOS,iv:mmH3u4sbrWaR1QaoajnbO87frxRe0zG7A+YjdPNmCB0=,tag:TxYQd2cGRuicBwOdLK+aGA==,type:str]
    SECRET_TEST_EMAIL: ENC[AES256_GCM,data:f69FmAm2lGwCl2L22kdqtx56X1Aq,iv:E+edW3BCf3JpcxSSAs2M/dlKaTcrJ6KLC6W178AEBwg=,tag:TnztT0nOQQuU2rBbR+qomA==,type:str]
    SECRET_PARTNER_EMAIL: ENC[AES256_GCM,data:msEcGW/9uhHRfIquqdAJ+hYlDjuA,iv:mYwoF6sXjeq6JGHO+hLB6U722pTr/LuUdrUp7+cjnqI=,tag:pl0+QAD796Ye6aIkbbIj+g==,type:str]
    SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:/dB2JBIaECvix42KTV0rS8n1Tis3AA==,iv:n89uaL4UQbwXs/zYBep7dFT7nQNl9ihIW6O1dpFL9LA=,tag:yeCk/MoJwbUMVJms0Tzglw==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:Jtmxq8IZGmLQAQIy4Jxs0jLyzsM=,iv:fE4wKcHFRujbwOnKGN6AWMV7mhU8EHhRP8tgCKsBYb0=,tag:BFXBzedB2vyk0MChlXK0Zw==,type:str]
    BLOCKY_VALKEY_PASSWORD: ENC[AES256_GCM,data:LJpXDcy2GV9jBIZuYibrDFMLifDyNJL+ecaE0pDlZlVaMpyI6MAgweKE5BnFwFEAeJklnWh5h8d7Wlp7f/th4NRItLkp4ad7x3vGdoImtFnPuvUEnXCu/HsqxkjkzTqULNe3zQ==,iv:0wBWk4xYREfVVU+MmSqqus57B7YAtigClin1AgY1WN8=,tag:Fi/dBvKC8nXAxb1aaqtyXw==,type:str]
    SECRET_CNPG_SUPER_USER: ENC[AES256_GCM,data:+nbpWfqzOUQ=,iv:WAmcM0yBfDKAzYl8yC9PbSOdLrIxlFhU3e/+Z1xH4qo=,tag:0XelfM+aYHnLAba7ESWKZQ==,type:str]
    SECRET_CNPG_SUPER_PASS: ENC[AES256_GCM,data:EBjv5mYnu+MQjgnrRY4XkarmE96nt+3FWKklMAnQ85kBr5LGG0UT1X/8mPDTtijIEtVeicE8io+kmpdSsIzOavZ0zu9Je5I6ReOb1e6uqDkM93/STsHSQ7y0jdzZ5NNko4MvLvLq4tZ+VmtfdwuxSWvRJb7OpgOYXtmQUBS86i8=,iv:XuKd27pTAW3lm3JWM+DX8VlPJG55KhpLG27dXMgC8No=,tag:eSuKagdLIujuQqBaJ88EtA==,type:str]
    SECRET_CNPG_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:8oao/Q==,iv:YKqa6gV5/JC+Yv12GxhEJTVGhcBlxx2Bqk/+FBq9OZs=,tag:igkDjn+8VpdCHu/oRTjT8A==,type:str]
    SECRET_CNPG_MINIO_SECRET_KEY: ENC[AES256_GCM,data:hs7y2DNKeaaKpQAg5VrLAkWBnSxu69gqM9aPZ6Obfe5ywphO6B3ZmQ==,iv:IV1ekBy1zQTC/W9mizLH6kXSn7cWUM4qKH4rYTS9xTE=,tag:ohzlsIkpGIQCpJSFszLlwA==,type:str]
sops:
    age:
        - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbkg3V2I4NjlYSFJpQnpH
            SlpVM29tdGQ2ZStmYk9NQlZBTWRVdWhDYm13CmpwaHd5ZTRLNTFFZm41UFVqZlVV
            V1FtNlBpTVNRTGhSZ25SZlJSWXVsT0UKLS0tIG5na0wvRU5UQ1JHWU93enh6TFls
            YlJYZzVhbjBYMU5hcWJMOE54d280REkKMlIkgLDuexvnGE92HtgjHcMfv8OLP1YJ
            Y90IFd+spJS9iMhG4qQe6vfKbKauGNpPAbcG0SDA4jseO/mc91yOjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMjg5SEJVY1RyR21hZWdB
            NUVKMGtFWXQ1NExBUUJxVStPNk95NEhXM0ZBCmNBbVNncmhGRmVTUFpSdU0yTFk2
            RjVwZWdWYm1RNjFCVnYvTm9jQUtLdjAKLS0tIGIvamRHUnN1UTRMd203MFBta1gz
            WGlzakc3RXFEOUh3MW1WS3JjZW5WTW8KVjSZIHcTDntNt43j2xk3YXNtFTdPvfNc
            w6jGw1NstZKq4XJbJY6lzeGBK84TrzqHQMpT9YIt503xekyh55U4Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T02:38:15Z"
    mac: ENC[AES256_GCM,data:zoBmD5LLeRrWl7i3KnqlLRYqUTeCx7yG30fmbdV+OS2U1+HDq68hivbZYrW21grxtHMYudTuiL7kqyRnIhI93H284v8Y3l8r8YntHiefhK0NSw93i7Tds00bh3qKeqrr/vANoHXe7l8u7Z08iaBUm9ZLInceSzYDvJZDXKpWWhE=,iv:vjishdg74T7b6HthWzuMulqpMSF9Lub9BkgaKmnr3bY=,tag:nclg6qv5Pfe6MpMIaBF9Eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
