apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: miniflux-db-backup-v17
  namespace: databases
spec:
  schedule: "0 0 0 * * *"  # At midnight every day
  backupOwnerReference: self
  immediate: true
  cluster:
    name: miniflux-postgres-v17
