apiVersion: v1
kind: Secret
metadata:
    name: miniflux-db-secrets
    namespace: databases
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9BpZtKvRwVI=,iv:fnKa11ww+tvDS1znULGaOOhqBnztLvWGuQQKQ0yFw7o=,tag:S9rPbnKV5SCbeZqU2r+kTA==,type:str]
    password: ENC[AES256_GCM,data:mLcRIxrdmbFrXKe+R+Bu3J19hrARg549r2MCFauPzPpds9+F6Qfpkbey8X+1TcR49ZmGAAo6pjstRhHQsmTPbA==,iv:byKMZpVJKpvfD7ALy8Nf+VJsL5jMUcxYibJAVemOu30=,tag:o4kRxiW1EZLcSa9ou+MGVg==,type:str]
sops:
    age:
        - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM0R2bmFPTW9PQytscHpo
            M2M1ZnYza3FIcUZwL3lDaEhLbmdQN3NrM1FjCjV2UjFIY2FFUnBad0ZQcVVsaStk
            MVMxalJBNDU3ZURPb2NuWHNBNlRQNm8KLS0tIENPOG5xRWZaREx0TUlnRUk2NUxS
            QjNrcHJ3UjY1MzJER3JFaU8yWGdEd1UKjTwY4RexkC+LHQHNnLElOdQteKXLr6vI
            6ou0O+2O/TaGz3KWJiqqFuujMskvcWDULJypcgnciaS7TQGrp2dv2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU0YxSVR2R0V0dXhXTm55
            QVZaTzN5dDZZV2xkZmNyNzVJblBOZHNaVXhVCktURXZzbDROckd2NDJhTk4vVm9P
            NE5JMFpSNWlpMUhhb3ZWWDVXMW9ycDQKLS0tIGNNTjFiSDRHVWMraTJlSVJITE95
            L2RHYTcrdWhXME9TQ1JvaXVya0J1bXMKmOLr1aEZf8dG0VEgAgQWJ3szWmG1vUIa
            SkUomaaxAe3Ppb4xU2pDjv6sE0jZdHsrNF6c4k0N94ZbWs1U1xmTdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T07:14:24Z"
    mac: ENC[AES256_GCM,data:x6Jgza8+LvzLIZjs2GUpGgHnSiAD8wv9XSOcI6Sj3vEVuJFXkLnM0XTSvRt1l+UyjuORxsmeXKf/JNVsU25ik3deUA4uP301Js+uhoS024vqFbv4fKKZ6nKLg2xdn+Lz61NSyIauZiW6rYwfajSl1TAQ8pTg3jdM3YxXddMCRgU=,iv:YYYSBrrzs91QNWM1NvogUeQZ0KO/D53EjZilAY1oYi8=,tag:3RhLQdyBFHNaRfCJMwcmAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
