---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  interval: 1h
  chart:
    spec:
      chart: operator
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    operator:
      replicaCount: 2
      env:
        - name: SSL_CERT_DIR
          value: /etc/ssl/certs:/etc/pki/ca-trust/extracted/pem
      volumes:
        - name: internal-ca-bundle
          secret:
            secretName: internal-ca-bundle
            items:
              - key: ca-bundle.crt
                path: internal-ca.pem
      volumeMounts:
        - name: internal-ca-bundle
          mountPath: /etc/pki/ca-trust/extracted/pem
          readOnly: true
