apiVersion: v1
kind: Secret
metadata:
  name: ig2rss-secret
  namespace: media
type: Opaque
stringData:
  INSTAGRAM_USERNAME: ENC[AES256_GCM,data:5Aj4khZAJ+z/wO0DKA==,iv:pGlGQ+lq5FaYXYVBJTI5+2+aYKH8F/4+rcJkzetOzpk=,tag:BKPlD4YWcoLJMOalLBuESw==,type:str]
  INSTAGRAM_PASSWORD: ENC[AES256_GCM,data:4nSYi1G9RAVJESnHiJB1amoqMbc5Gv5Uu/6EOvyQ1fWZKAV/E5E2xUFQ6jQkTFbGFfdoX1VGNF2qcS8WC4gWdlHdBdPfXQvA6eBGVL9E2XLBgSQzxupKwPiN,iv:ydjKEufihN/ayxG4wobh5Tqf0ObxjWgooUt5y0CbuUI=,tag:CJceFrwg4+4LSScH5Xx4rA==,type:str]
  INSTAGRAM_2FA_SEED: ENC[AES256_GCM,data:nBH00ThaPugCAJcxFH5xHXpuwQnmQlP73uVZcCf2ZNYcunXSp5q62V3NoEvYQQ==,iv:6vtGL3jAXoz2fyOFDGhyLTn4YhXnetbOIJJ725cc+Ew=,tag:2wXugBnRXS2QFlYTHX3Mwg==,type:str]
sops:
  age:
    - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaGRGSFVrMjl3eVI4SGd0
        eEVpb0NIa285UlR6TTU0dWsrYkU3eGxwQWxNCnE0VXg3REVKVW9wY2dwTFhHbWNO
        QWw1bnZUaGtDTkpmTUh2U0lWOTFvYkUKLS0tIGxFSng3TzRadEc1KzBvcXdxZW9F
        dS9RVDBnTVJsNGEwVHJpa09FeHJDdGsKUikU7jWSqHq+0Nh7Ax7AXxunnsEz2BX0
        DDQ6LD+NcXGj8o17YZjXzofJQbrw2isp8pNNz3jIKr0mElzgsA6qYA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd3licHh3aUtaazd6RmQy
        V20xeUhmUjJXQmh2Q0FISnV3Tk5YaUJFNlZFCjFUcVJ4aEVQWlJWQU03aTAwV3NM
        N3VLeGN4eGFxaFZpRkcrdHBJS3ZlR1UKLS0tIEtQQ3ZxV3A3Y2ZEZzlxUUYxc1Vh
        U2pHT0lHSTNucjNHc0VXc2pncG5PLzgKuwFiSn202t3IWu37INmYyVjx/1LNFw6w
        Qthc2cG5bJ348wA/DtiO00MEKBQqvTbMjBoq0VhnE5aIk4C13UcecA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T22:09:51Z"
  mac: ENC[AES256_GCM,data:uOnAgkZ5/eWBNlqicC9BAyRxqJF/7JYXKYFIyeBjzFmtQAXA2WKupoXJIMOYTeVQykz7XMbK5mtINOOwUyjqIcnH9ux/6vf5+6vXZzR4r9qnhsfNe/vEyFnoSVy1oARetXQPOw/cO8ZiJETotmgcjrxN0xwjGneMYPPJKIBzPgg=,iv:9gAQlkX/mWCs2lyIfItCnEePPA/0oV7iQzZvVGtESJE=,tag:7x90yugSw/IXWxtGZFiEYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
