apiVersion: v1
kind: Secret
metadata:
    name: ig2rss-secret
    namespace: media
type: Opaque
stringData:
    INSTAGRAM_USERNAME: ENC[AES256_GCM,data:uSoV0vPT+LJ4pw==,iv:7otR3vc4iFHkiQIE0LBOyWzaRqteAT7DrmtM5Lo4g34=,tag:3q36fpr3a2l8sMgTDk8nxg==,type:str]
    INSTAGRAM_PASSWORD: ENC[AES256_GCM,data:12CsNfmdWpjWdGzYQtpI9ML4/BPT/Lhm8iKpVwl5MNi0zU35L+54cNHljVZLXLDFQPRaUne+f/wTRGneGeY6ah/CGxw2jRv8,iv:SKckqVAiE//epBVvP4XJo30gKdBi/y+OSC0K34MQrqQ=,tag:u8V1+SPFD7ESkZEcxamPkQ==,type:str]
sops:
    age:
        - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMXNZaDZBZlBOd1ZxN1hw
            Tjl1dFZoeDlPa1o4MEcrMDhQUnhBdnJ0MEMwCmQzQko5TFVrbHZMSTdmWU4wTUVW
            R2hhVkJrcUJTZGJOTWRXdUtFMmZNTGMKLS0tIGtyT05kMmVsekRrWGxuOWdQT1dB
            NHducnZzUGV3ZGEvc0VOMVEyMUdodW8KUbplWXKdVWi97tx1KnjG1onfWH2tWRLM
            GSW1RCIyNP+i/trbpmukw9zCtA1iH576Si0iKyC7mUG5oXni/i4ukg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SytkYkk4MkJiK0VTMVZC
            WEtpemJhYVBWeElnMkU4K28zS3Z5cHp4d25FCkRSQ1ZZRE53M0cxTW5NTVliaDc3
            Y0JZdDZEYk1YU3liUUZDRVY5YlJjN1UKLS0tIGhzTTF4SmZRQkNzQWNWNHVLR1Vu
            dGhMcmhmS3pFaHh2R0w0cFBvU2tvOXcKoX/AHIKR0V81mgZCVeauyIuuH4uPpdgC
            ZhWONFd0oWf1FcGrp1sxzshQPHKp9IPfcPh2FuKCsGKoAWHuwghRRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T00:37:16Z"
    mac: ENC[AES256_GCM,data:bEnWzJTn6jLSCKFUZ4vFkYAWLnxB/JIIG/zg7m89E2gE/mLoNgM6e/ZxkAE4X9ShAG5HsuZt8GSVCC5Apph+HMNZfXR7NpP6PGb8RK8jDGOPKkfNS8Dv27tGJmOr6/TKq4w8y4YsS1X0OXGVe4QMDd9jXV6Sdnxub5HU3/Bqjys=,iv:qtWgqw9Lt07xWx1tSZ9wSbRgsTW0uswg5/oUCef03yk=,tag:W12NlkkGdej9mgaeNHDXgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
