apiVersion: v1
kind: Secret
metadata:
    name: ig2rss-secret
    namespace: media
type: Opaque
stringData:
    INSTAGRAM_USERNAME: ENC[AES256_GCM,data:wQsDjfixGnHIOg==,iv:0CLzFjnI35YocYaSPd9E7nx4w5n+GXB58hK7QPwaWAc=,tag:HXxGuiBxnJWmjw4oIkAORw==,type:str]
    INSTAGRAM_PASSWORD: ENC[AES256_GCM,data:HwPU+m5otx1yVy2uQ4m6z7Rfr0DkiDxWCtI/L5gwvbmR4Evnci6qjCFpdtcIlT8hcmX4lmWuyQGOT7iipLfCYiUr5rzkK0UNrB80y9pkrztqQ/xKM8te+XTE,iv:MKZ/3DSEXGgr6DwRc+4TNIao1Zcad1HvUA2TSs/8+tU=,tag:+KcT2lIXYhUZyawcep91lQ==,type:str]
    INSTAGRAM_2FA_SEED: ENC[AES256_GCM,data:Kz0b2rCEKi+S+Yv5wezqdwh44AJu/GwQUOaiM0YU3NYDi76vAvGVBFBJo1M0wQ==,iv:M9yyVVeqJqpS6ZCCSk1BiwFBObjGH+V/w785ukK54WM=,tag:vnU7DfXWOxUi435AQy1n1g==,type:str]
sops:
    age:
        - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cTlsTmg1SnRsZkQwRWdU
            MHVvUzdrcFUxWDh0UEJRZnJ4YUovYTNzNWpFCi9nUytJUU95ZWRwUm9LTjlBL2Rp
            OE9rSzgvK1haRmlSYm1pcnA1ZVFmaEUKLS0tIDR6ajVOeWxsRFFGL0R3MVdsOGp0
            aGcxTC9STGFzTGhFNWY0cFV3ZjRUTGMKS6Pj1zGaB/ApD6mr4LGKMp+e+EE/vXSi
            XBzOC9m5/zoJqfQkwsAa4BcM3C2XvSSK7l6tegJiSzwpbFc8Ho18ig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TDdRU0VVMFFveGl1Y293
            NU1nSjM0SjFscHU5UmFKWThKWlBUNXRXNHpnClVNN1FWaEh2MWVjWkNGZW54K3Z2
            UUpVT0RFdnpRcnVpZUFoakhaT2RVR1EKLS0tIE9scnpzR3lram10QTJLVklndG9n
            ODgyRmJsRXp2dTAyWndYMG92NTlNMmcKHLkEeV/RNv6GM8U1Nq7Dn3WU6x+VBEwG
            ETEAvjZoWERPC4fJH7iuMLWK/3f2KaI+hDYKEQ+lELvuVhyRzdiEQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T06:22:27Z"
    mac: ENC[AES256_GCM,data:ap7ucN/yb+zh7ELJF0QUgKUAeQNJKHuIv4U3bkUeqNZQ0wJve744lIJ94gRR0x3y1a4R8YjUU25scf73EjFyE9HqOvfpTvOovrNHXU30t/yqbc36kMcCVNlUvEbJfCK+T+G2KsprsMt+dav7PwU+lzTviNAvPdjr2zuEkHe6zz0=,iv:r+bRaV2pfbgMuvn5FRTtCZSuIi/VohfKiZSrOMeRQng=,tag:NPYcxbD5bpJtYsqfB8U8Gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
