apiVersion: v1
kind: Secret
metadata:
    name: ig2rss-secret
    namespace: media
type: Opaque
stringData:
    INSTAGRAM_USERNAME: ENC[AES256_GCM,data:UA09rb/BD8i0Ww==,iv:ccEL60kWFxjcturq3jQ0NraMWsc55/o7ADOI0mPJAkA=,tag:4W1GNa1kcxfBVCevA5SpOA==,type:str]
    INSTAGRAM_PASSWORD: ENC[AES256_GCM,data:F9BSOEnSk8h6VsHLV79nhqDErf9qjLGIvN04Ah+riC/s4GGTsU2dvAM/fL0BUgsvSGIe9ETUHkD2581Bsob8ZBjbiA2cH2qllRCdgL6TkHbpDKTR8uNWCdpI,iv:4inoFxjxI64iglGKNdBmj94jUswkilrRhJOPBF2D4sg=,tag:nWMmscnla8YtJYupPy22dA==,type:str]
sops:
    age:
        - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L0d5cGM1Q3JYM3k2YVlz
            UkdvTDV6Wnl2UHlsbmpvSlNpU2V4T1pSQ0RRCjBrbExPSWxtM0I1ZDhIaDdJcjVU
            dFhKOHh3elAwK1U5aXRma1Z3Ly85dm8KLS0tIEdWbXd3YjZnUHVWbWFhazBDeXZY
            QlhRMmJtTnArWHA1ai9uU3UvNGtpeW8K5JBf98rIglBSBwAreoKx3ocmYrsw2FfM
            8n2+26NCSWclhdqIynfryxKriP42i+5xPLGsx8hkKx1P2C/VV5wJfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRCtZTlBvNlFlMjBZd21V
            alMzNExxeDhLdnkrNGxGR2VNaExmVy9qcUFjCmphOS8rUzkwVmJFcDB1RDZNbkI4
            ZDBzWDV0cFF0ZVhlQlM4eHVOd292UFEKLS0tIGdreTFnZERib01VekM1Sjg3M1BM
            b2xyUnNZQXQ1Z0FjY1ZSUEdGOHRpZzAKipwcRS2gEHXIssbPz7o/8BPF8MSHA2rT
            hYgBljo9ReE4xZeItGtaEqKUFyXkFo1tQcbcdz3UrqmDgY7jKDTA2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T05:49:03Z"
    mac: ENC[AES256_GCM,data:G3pgLUyLzJgePKTBRAUFnuyGhe8imbIYf0XvY3m21Sd1E/aiVqqaHu9GMTMgBOlpUU5RSK9UU6qqMEpa+gvLR3f2Bfudl4CWSenrDU9uuXxLsy8dDCFuU1WGVpJrOzcX65WWjlk5UW5wHOY8ipGbUH+OWjqLNycbNgOqZAXBCF0=,iv:ggmMd5CZqlLpACo5wE/o1J2ikH27as3FenLkUjoofMI=,tag:4386ls415biRgE1p1+bSVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
