apiVersion: v1
kind: Secret
metadata:
  name: ig2rss-secret
  namespace: media
type: Opaque
stringData:
  INSTAGRAM_USERNAME: ENC[AES256_GCM,data:vdkCqQq56B3DsSoo2Q==,iv:aTvZYZIQguzwJLXKYyD1WTqe44oTTZ8+R4NIIWbdArs=,tag:CEX1VuroR0XQiIY2MHoGrg==,type:str]
  INSTAGRAM_PASSWORD: ENC[AES256_GCM,data:D5s/Zt51fTRCL4uVcB/J2Ugzi46hGZ56JkCPA2kPyrSCemQmYM19aibrLuLs4lIqhqDQvqnPlcV9ze1/ryH2jh3zg5LvTyhE6Yh0Zi91wOAL6BddAc2gDz4k,iv:z4RHqD6yy9ETvAQwCcdfsPjKvEcBTaSjifTfHEofCxg=,tag:QAXwL5+cxCvsZCpSl9R0jg==,type:str]
  INSTAGRAM_2FA_SEED: ENC[AES256_GCM,data:FO+hOYYjJIdopgrqBs7POlcwewh1nWA84JadSStiw5kcNziveW2pMtQyEK8kaw==,iv:3mkCF/x6xP7XadpaahQjcRzjzJ+EGiR/y7t9EFhlHw4=,tag:/Ht9teJ9fI9gVMfXVLJqcw==,type:str]
sops:
  age:
    - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN29nTGtLTnV4czVSZzVl
        dE5IOHZZRGthL3Ftc01DdEhCMzkvR05WY0RzCitRNlJlam1zM2h6UnhQcXVENHNQ
        eU9MOTBscnpqTnNUUzZyMjZGN1dCQVUKLS0tIHVGZGQwWk14RmVLYzlvdkQ4OXN0
        eFpINXdWOWt6RmdNU0pLY3ZaOTJYLzAKylZUKGgmseHIm6b0kJaqCRXzAuyvQlUD
        A54/dHGCj8mIdThrpDfsk9MnBFRNPDTPNZQ31zOobDjJ4Y3zyRbAWg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMnIzYytxMmRzVGxuT1Fu
        S0J4Q1hrOVZIM1dWWkE0blFKRlZMUjFZdGl3CmZiV1Y2RXpweUxtRkJXNlFVQjhv
        VWNVVEZRZkQzYm5CK0ZRYnFnckN5eHMKLS0tIHVlSTVpK3dhMGlNZllXeVpyeUkw
        czBTczk4Si9qRmFxWEJqMGU4RUFtY2sKhT/qRp2OaOVWoP1Ef5beJ3wZ8J59JzjW
        Edwd0GqiGcq7gH13P2WZ674rMlHLeyw8p9QY1SfsCichYY7DuwgrEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-29T21:14:47Z"
  mac: ENC[AES256_GCM,data:HWFMYvtAeXzVxokj1JneQ9UinO10J+dWKxpU4VXrwiy9vfIc/kFcZHizUGOfOL5kxrzRk8Cp++O3XuEXIvnN+h+IO/CjzB9yXI4POWNf3xPgoVZ7PADe/rIGwB/zD6+nB6wqOjwm47TKBJ23SwXh4wdEVLbHXQNFKmdBZo/rMC8=,iv:Lae4iBrOjOq/xdzDwcnroFxSoL1TdblakQxZQFaDJ1Y=,tag:T1kaYJ2e1/S1MCIhzh327w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
