---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-local-path-provisioner
  namespace: flux-system
spec:
  path: ./kubernetes/cluster0/apps/kube-system/local-path-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-cluster0
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
