apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-secrets
  namespace: media
type: Opaque
stringData:
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:2gpeUo+WMw==,iv:tmdcyrO7Hmkqo+W/DFqKPmMYKlkwEPcfQ2E8KKDQzng=,tag:R6p8zYkytX1AmdmBRXUecA==,type:str]
  OPENVPN_USER: ENC[AES256_GCM,data:UIQk4v3Z1asgJlhtfIxrNaPGNx2ccdjH,iv:VAu+QTUF3tivTOo03eCaBxdQlEzz34SV+k1L45wJiNE=,tag:htss2J8NRUX+wpFjoNAsNQ==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:TNlZHQB6evhHzYs6tflvrX4xIg6uR5+v,iv:j6dXrDt82k4/gZ/zmp9uG8tiCAgnvZ31lC+EmBVmqwE=,tag:hVeEtrZzbWTgQU6hnk0d/A==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:sW8eGYq5tjqxMz0=,iv:PuWaLNghf09TQnne78mVhA9xVn2/J5xWmS8ZViqhtSw=,tag:d5CMdykg6DuCYxBfHJ7NbQ==,type:str]
sops:
  age:
    - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb0JlRkhTOWJWanFEWFRi
        d0FZeWsxRW9DYmJuczFDRjNnSUVFdkxUNTBnCnAzY0N3MnZyZFYwQm1uVm1IaEhn
        Z2J4czU4RWtlelFnOTd3bGVTLzE3clEKLS0tIFVkbG1CTGROTE5BMHlnUUV6ZmI1
        Z3l2eUc4MjA1eVRNdTlUR0htWkUraDQKA05AuImYNmmdYIlHMmZ8mSJUJ1PB6JW2
        6/pYqXAIW2igx3ZekQT4m3cR7Bycm+2a1tTc/CGhuWk0RbtS4Po8KA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cGFvQkpucmQwSnlZYlAx
        YkxaKzFadnRzd2ljZmQ4V2xXMlI1a1U4YVdVCkRSZlNtTnNiZjBNZDdnUmFtYVVn
        RUhDOU9QRUZoT0NrYU84MG1UUktJZlUKLS0tIGI1eEFLZFprenlWMWUvbGIrOE1M
        aTJTZ3M1T2pXc3FMWlVjZ2xXcVNzMDgKA9zU26RKz4mnhk7B1hw/5ymysU3lmhPy
        izuc4mDHjy3iauGRj7m6Y05k+LHrd5XFVowL9yoVLd2QfUr8YvzXJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T07:25:19Z"
  mac: ENC[AES256_GCM,data:Ymbd1OG56ru3CH5irGrMF7olmsMwG3v6wpI0rsxxmjiwa1TxMvMZCf1vZL5WPjO8LqZN21RnDxcjmKbZvDPN83SBzBp58v/kbVIPrJyLFp9QF7KDdHVJlR7K1QWEIKrP5MfsEV8gRLRGbRkSIhkFOXWaPQ4rO8El43ijTZ0D0mM=,iv:cf1dLJfKvjPnbx+HpnBjuhrWWb/7LUPjbedUUAd+75c=,tag:QaRgKXumLulil1egrHXsbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
