apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-secrets
    namespace: home
type: Opaque
# seems to need both keys, idk why...
stringData:
    password: ENC[AES256_GCM,data:aQwAaHLmDISTrp5LEF6jjlUsusmYE3Eg9cm1tMk2Wi86GiVRWV4pugQ5sGxyzji4N/ydbHOWfu+5Mfqy9OA9CQ==,iv:jViPpjWJaZLYE4LFmLIJwVo+JjkF+F2ZjfHpCTQ0c1M=,tag:+YfCaOtnJeIITgu4t9rfQQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:rrWFEB8owzN8b2hpBc0aig/Rb1qDZaw2afL1uYvG6u7p9HrXlYfLtII7CCJXnAZlYRfwwgfgzQkQqxYMmDnkmg==,iv:D9IkZBt7qynSEQcnYy3VnGT0IH0exKWdVuB0Lkmxmew=,tag:sXgatjv3DeaPRfkzaJIeKA==,type:str]
sops:
    age:
        - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dGd1R3FJM21RRDkwUkZY
            bnpBbXRLU0F3UElNTS90YlFQY21DWFlFUGtRClAxMVlBTEZYdDlpdXROQmJJNVlo
            YkdsNDRKNWh3blkzWXNLQW1tdFpuUDAKLS0tIEdib3NtSVVZcE5sV1hQcjJoeUkx
            UlhuNXdjMnA0cHVzQ3h6TU5JQkpSV3cKiMRpw4RNwHx6b4GFjP80yABVIhubJl9S
            SYH1JqCjEveayQXcXhELcATt2tgV6TKlHWBhJU4JxuoXjRMOPuZDOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MVNWeXZreU5NRGNVa290
            ZDd2SjJuZ3dqWFlKUUl3MVIreVo3aVBUdlY4ClcvVU9HRm1OSG5uelRaQm9KQUhY
            eTRTWVNZNDRhblVDbU0vdC94RGhwcVUKLS0tIDRETDRpdFZuSlEweFR6ZEh3UldE
            dXhRL2xQTktUd3BRSjh6VGdMK0Y0b0kK0J/WQPXCjvt7vQq9EcP+8LbeA5MgWYuj
            7lmGD2MVixW2trZyLAsW0p3NFRelaFz/Gt4Mxc+KFdoKpXpo/lMR5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T23:04:33Z"
    mac: ENC[AES256_GCM,data:6wUlo3sDcDV0eymrPKCFq9hn3+emuUFpGiW58T15TDNpGil0ijAD/Wl8A20AG7T49Y5auOV0ShEXmL0rb4Gi16ULcif8leh3HjY/T93D2zQksjoyfe4GNW50f194pTzE+53TByF0S7+yrJIuKlH4IjQ+yGFcUrDAcO3ed2woDl0=,iv:H5kyU+WuSalAIeUQIOurSNKY4EMh4GOmtLL/e2jG36M=,tag:fh/EmW+jkgTiQNiPvnjN+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
