apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
    namespace: media
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:DFho,iv:RR7cBD/nPgrVPg/fR0UDwZPW2iJ3yxKPd4JgOQAguXg=,tag:8V9xGBZccUIoaYBt/snl6Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:4eSUyUdGRqyou4MTy53lIBKhIFsNmecalaLJJZBpw8rFGUUsDeYv+s6vO/D/iteHzWTl80GJUsKLbyv6GahqUQ==,iv:uCSvEg/E4Y2dCDpFIoM7FBUZ0OILyvivnzbhvnuOys4=,tag:wpJrCAgksY6ChBJg6SV9cA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:CRg/GoRVeRZ2LOLAGiWMEsufBBntlYMUcYUJcYLWFzYJA1m+7A9VmE5i3+dGzrrhRV8uyI7VaT4zKjnr556P+DycBpba1S/E2EG2yp/EwpxJFD3xcCz82yHUmBM8iyzY5E9aGQvBA0c0K4BKUeC+6f4NNoDMNUYSTZf6rhlr87knGBJiA5mtdGF83mAwH94gy+pKvw==,iv:CHN++el5bRfkRSdDO454RYyHjSNeJv0H1grdA3SGT1Y=,tag:p9hgq4F3CiFvTN2P6MAUAw==,type:str]
sops:
    age:
        - recipient: age1582vh25trj6w7klwt38d44n5nr8njr8rrxxx5kcfu3y2ezx9ss3s6j24ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR205SWhxTkVROHViU3Fv
            eVZpTUpOMXZVakNYYnpEVlNGSWdLUjRab2lzCjhHOFF2SHNsNWNoMUpNQnFpMGJn
            NDcyMWx3a2VPbTBNSk1qQmJNMzBjQzgKLS0tIDdPS3pxbC81YnpyUkZDMFduZ0Ru
            dTQ0UjM5OVQ0MzRXRGZHaW8zdTkwMW8KhLEK/hA1l91DuP86EQE5At/qHQc7gSdj
            1KJwYh+12gjpR22OBzjjjLe1BiANSDSXcSTlTCFQJtP0bHsRehj3rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDK3pjYlp2ZlZCNldSZFRl
            WW0yQ2I5THQvNldqbWpvZGdrOStlY0UxSEMwClVWaGtFZVRybHNvZnFHZ2RaNTFH
            ZzI1djg2dmNoTUhWVUJ6Uzg1QWhCK2MKLS0tIEVnZnhSSHFVclF1MlBFT2VFVHUv
            TGNiZnlON3JKd0J4UDg3T0VmT1BWODQKB845iUTJZ/R2j7b4Ah3ppoBpuqLSpPN7
            7f5su8lGtF814KCttqvwwIe8mtHO7tldlVm0a1KMlJX6+TwHLdI7hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T07:21:41Z"
    mac: ENC[AES256_GCM,data:rRro4Ij80n3HBC43mIvk7wFYDSRYntDJ4edqell79j42SzaVESUrXb0OxFjGDM94BJVnnMWR4kjXB+i/zOGQdpEf6FAM47RcNO35uH5wBuzm7KslCiYYbIoTow7FgDVIo5JyoPhXlDerYV9+oFgWQuhV806qKhjrei6r3z25yLU=,iv:GPpKZPZnoAnZMklkLqxCTuBldimU0OxZjVnqQpZ+EGU=,tag:LCfa7ukyS//+BVjogaufxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
